version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: "zookeeper"
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    container_name: "kafka"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "users:1:1,:1:1"
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongodb:
    image: mongo:5.0
    container_name: "mongodb"
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db